const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const {verifyToken, checkAdmin} = require('../middleware/auth');
router.get('/stats', adminController.getStats);
router.get('/logs', adminController.getActivityLogs);
router.delete('/logs/:id', verifyToken, checkAdmin, adminController.deleteActivityLog);
router.get('/users', adminController.getAllUsers);
router.get('/feedbacks', adminController.getAllFeedbacks);
router.delete('/users/:id', verifyToken, checkAdmin, adminController.deleteUser);
router.delete('/feedbacks/:id', verifyToken, checkAdmin, adminController.deleteFeedback);
router.get('/stats', adminController.getDashboardStats);
router.get('/favorite-stats', verifyToken, checkAdmin, adminController.getFavoriteStats);
router.get('/recipes', adminController.getAllRecipes);
router.delete('/recipes/:id', verifyToken, checkAdmin, adminController.deleteRecipe);
router.put('/:id/premium', verifyToken, checkAdmin, adminController.updateUserPremium);
router.put('/users/:id/verify', verifyToken, checkAdmin, adminController.toggleVerify);
router.put('/recipes/:id/premium', verifyToken, checkAdmin, adminController.toggleRecipePremium);
router.put('/recipes/:id/classification', verifyToken, checkAdmin, adminController.updateRecipeClassification);
router.post('/import-recipes', verifyToken, checkAdmin, adminController.importRecipes);
router.get('/community', adminController.getCommunityPosts);
router.delete('/community/:id', verifyToken, checkAdmin, adminController.deleteCommunityPost);
router.get("/history",  verifyToken, checkAdmin, adminController.getAllPayments);
router.put('/reset/:id', verifyToken, checkAdmin, adminController.resetPass);
router.post('/packages', verifyToken, checkAdmin, adminController.createPackage);
router.delete('/packages/:id', verifyToken, checkAdmin, adminController.deletePackage);
router.put('/packages/:id', verifyToken, checkAdmin, adminController.updatePackage);
router.get('/coupons', verifyToken, checkAdmin, adminController.getAllCoupons);
router.post('/coupons', verifyToken, checkAdmin, adminController.createCoupon);
router.delete('/coupons/:id', verifyToken, checkAdmin, adminController.deleteCoupon);
router.put('/coupons/:id/status', verifyToken, checkAdmin, adminController.toggleCouponStatus);
router.put('/coupons/:id', verifyToken, checkAdmin, adminController.updateCoupon);
router.post('/send-newsletter', verifyToken, checkAdmin, adminController.sendNewsletter);
router.get('/user-reports', verifyToken, checkAdmin, adminController.getUserReports);
router.put('/user-reports/:id/status', verifyToken, checkAdmin, adminController.updateUserReportStatus);
router.delete('/user-reports/:id', verifyToken, checkAdmin, adminController.deleteUserReport);

router.get('/recipe-reports', verifyToken, checkAdmin, adminController.getRecipeReports);
router.put('/recipe-reports/:id/status', verifyToken, checkAdmin, adminController.updateRecipeReportStatus);
router.delete('/recipe-reports/:id', verifyToken, checkAdmin, adminController.deleteRecipeReport);

module.exports = router;